### ISSUE TITLE
Can't be used with current Kitura

### ISSUE THREAD

**Issue by gormster** [IBM-Swift/Kitura-Session-Redis#3]
Kitura is currently dependent on Kitura-sys 0.24, while this package is dependent on Kitura-sys 0.21. The two cannot be used simultaneously.

**Comment by shmuelk** [comment]
@gormster oops. We missed that one in our last release close efforts.

It should be fixed now.

**Comment by ianpartridge** [comment]
Closing as fixed - thanks!
