### ISSUE TITLE
product dependency 'KituraSessionRedis' not found

### ISSUE THREAD

**Issue by CosmicYogi** [IBM-Swift/Kitura-Session-Redis#36]
Hi, 
I am trying to use Kitura-Session-Redis in my project but can't do it because when I am trying to do it it's giving me error "product dependency 'KituraSessionRedis' not found"
I mean the dependency is fetched from GitHub but when I am adding this dependency in the dependencies array to use it in my project it's giving me the error.

There can only be two possibilities of the name of dependencies and those are either "kituraSessionRedis" or "Kitura-Session-Redis" but it's giving me an error with both of the names.

Added image for the reference.
<img width="573" alt="screen shot 2018-01-02 at 3 09 07 pm" src="https://user-images.githubusercontent.com/7416058/34483377-109c5518-efe4-11e7-827b-90843ed8e3e2.png">

**Comment by Andrew-Lees11** [comment]
Closing this issue since the PR has been merged and tagged.
